name: Go CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          go test -v ./...
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64 # macOS arm64 构建需要 macOS runner
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build binary
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o szu-login-${{ matrix.goos }}-${{ matrix.goarch }}.exe cmd/srun-login.go
          else
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o szu-login-${{ matrix.goos }}-${{ matrix.goarch }} cmd/srun-login.go
          fi
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: szu-login-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
          path: szu-login-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
  build-macos-arm64:
    name: Build macOS arm64
    needs: test
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -o szu-login-darwin-arm64 cmd/srun-login.go
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: szu-login-darwin-arm64
          path: szu-login-darwin-arm64
  package:
    name: Create Release Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: Create Release ZIP
        run: |
          cd release-artifacts
          zip -r ../szu-login-all-platforms.zip ./*
          
      - name: Upload Release Package
        uses: actions/upload-artifact@v4
        with:
          name: szu-login-all-platforms
          path: szu-login-all-platforms.zip
